# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-16 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20181216_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userhead',
            field=models.ImageField(default='uploads/default.jpg', upload_to='icon'),
        ),
    ]
