# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-16 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20181216_1943'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data_yunpan',
            fields=[
                ('id', models.IntegerField(max_length=11, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('href', models.CharField(max_length=100)),
                ('downurl', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('img_url', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='userhead',
            field=models.ImageField(default='uploads/default.jpg', upload_to='uploads/icon'),
        ),
    ]
